name: Unit Testing

on:
  push:
    branches: [ dev2 ]


jobs:
  test_push_request:
    runs-on: ubuntu-latest
    steps:
      - name: Run Test Case
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0
      - uses: actions/setup-node@v1
        id: unitTest
        with:
          node-version: 16.19.0
      - run: npm ci
      - run: npm test
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://services.odata.org/v4/northwind/northwind.svc/Customers"
          method: 'GET'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
          echo ${{ fromJson(steps.myRequest.outputs.response)}}

     
    
     
        


       
        
