name: Unit Testing

on:
  push:
    branches: [ dev2 ]


jobs:
  test_push_request:
    runs-on: windows-latest
    steps:
      - name: Run Test Case
        uses: actions/checkout@v2
      - uses: mathiasvr/command-output@v1
      - uses: actions/setup-node@v1
        id: unitTest
        with:
          node-version: 16.19.0
      - run: npm ci
      - run: npm test
      - run: echo Today is ${{ steps.unitTest.outputs.stdout }}
        continue-on-error: true
     
        


       
        
