name: Unit Testing

on:
  push:
    branches: [ dev2 ]


jobs:
  test_push_request:
    runs-on: windows-latest
    steps:
      - name: Run Test Case
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        id: unitTest
        with:
          node-version: 16.19.0
      - run: npm ci
      - run: npm test
        continue-on-error: true
      - name: Get today's date
        uses: mathiasvr/command-output@v1
        id: today
      - name: Check on success
        run: echo Today is ${{ steps.today.outputs.stdout }}  


       
        
